### ISSUE TITLE
Issues with bottom menu

### ISSUE THREAD

**Issue by felixhahnweilheim** [cuzy-app/humhub-modules-clean-theme#13]
First of all I really like the bottom menu. Thanks for adding it in a free module.

I am testing on Android 13 with an up to date HumHub instance and clean-base.

1. The active icon has dark background when I first open the site or reload it. When I navigate there from another page it is just darker icon color.

First page load:
![Screenshot_20240316_075236_Chrome](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/84990763/dd54a992-a230-4c49-91c6-18e634a13a2d)

Navigating to it:
![Screenshot_20240316_080401_Chrome](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/84990763/21434056-c9e4-429a-b221-387b6b704515)

2. The Space chooser does not show at all.
![Screenshot_20240316_075300_Chrome](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/84990763/26029def-eb3f-4fa4-991d-f806570688e2)

**Comment by felixhahnweilheim** [comment]
3. an issue with the sidebar. The menu is halfly hidden (but still accessible via scrolling).
![Screenshot_20240316_085313_Chrome](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/84990763/d5b0a5c7-e486-4487-853a-ce4c2df436e6)

**Comment by marc-farre** [comment]
@felixhahnweilheim thanks very much for your feedback.

1/ Fixed in commit https://github.com/cuzy-app/humhub-modules-clean-theme/commit/0d9022c7f4e4e8a9bbd57572c8be68908da3eabd
It was due to the fact that when you click on a touch screen, it simulates a "Hover" effect, until you click somewhere else.

2/ Should be fixed in version 1.7.1: https://github.com/cuzy-app/humhub-modules-clean-theme/blob/master/docs/CHANGELOG.md#171-march-11-2024
Do you still have the issue?

3/ The solution is here: https://github.com/humhub/humhub/issues/6889

**Comment by felixhahnweilheim** [comment]
2/ Yes, I am testing with 1.7.1 (did not test 1.7.0).
I also flushed the cache.

Sorry I have no time to investigate today, hopefully the next days.

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks! If you want, I can check what's happening on your instance (in this case, send me a PM with the URL of it and a way to login to see the Space chooser menu item).

**Comment by marc-farre** [comment]
@felixhahnweilheim

2/ is fixed in commit https://github.com/cuzy-app/humhub-modules-clean-theme/commit/9e0e5dd6d86c239a5fc9f0ed675907eb8b7266cd

3/ will be fixed in HumHub 1.16 from PR https://github.com/humhub/humhub/pull/6890

I will release a new version soon (I might work on content add-on such as comment, like, reaction, etc. before releasing it).

Thanks again!

**Comment by felixhahnweilheim** [comment]
Thanks a lot for your efforts. I can confirm that 1. and 2. are resolved.
