### ISSUE TITLE
On mobile, top menu dropdown notification panels are not centered on the screen and the logo is hidden

### ISSUE THREAD

**Issue by kiwiradler** [cuzy-app/humhub-modules-clean-theme#16]
Hi,
as you can see on the screenshots, iPhone 14 produces some representation error regarding the margins. This is when you chose the messages or the notifications button at the top.
Another thing I miss is the logo of the instance which was, were the search icon now is. I miss the comfort of clicking the logo to get back to the dashboard. Thanks a lot for your work! 

![Bildschirmfoto 2024-03-24 um 13 05 25](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/45717431/8ca92c4e-5bfc-48a3-a03b-6ec69797e354)

![Bildschirmfoto 2024-03-24 um 13 06 02](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/45717431/018d35f1-fd2e-45ab-b3ea-30dadcbe1963)

**Comment by marc-farre** [comment]
@kiwiradler Thanks for your feedback.
Should be fixed in commit https://github.com/cuzy-app/humhub-modules-clean-theme/commit/6fb91206b23fd9dfe234b73007f26d19d1e3851c

Can you test?
1. Download the latest version of the module: https://github.com/cuzy-app/humhub-modules-clean-theme/archive/refs/heads/master.zip
2. Replace the files on your server with it (in `protected/modules/clean-theme`)
3. Flush the cache (Administration -> Settings -> Advanced -> Save and flush cache)

**Comment by kiwiradler** [comment]
Looks brilliant - works perfectly fine! Thank you!!

**Comment by marc-farre** [comment]
@kiwiradler thanks for your tests.
I've just released version 1.7.3 containing the fix.
