### ISSUE TITLE
Mobile: top bar issues with added items in the notifications block such as the night mode button

### ISSUE THREAD

**Issue by felixhahnweilheim** [cuzy-app/humhub-modules-clean-theme#6]
Hi, with HumHub 1.15.0-beta.1 I have following issue on my phone (PWA).

The menu icon from topbar is missplaced and the search text overlaps, see screenshot.
When I swipe to the sidebar (e.g. dashboard), the topbqr shows correct. But when I swipe back it comes again.

![Screenshot_20230824_223951_Chrome](https://github.com/cuzy-app/humhub-modules-clean-theme/assets/84990763/259464ca-3460-4015-8ce5-d3b857994f02)

Clean Theme v1.5.0
Theme: clean-base

**Comment by marc-farre** [comment]
Thanks @felixhahnweilheim for reporting this bug.
I've changed the title of the issue because it's caused by the add of the night mode button and not Humhub 1.15.

The commit https://github.com/cuzy-app/humhub-modules-clean-theme/commit/dd2f83b81b78cfd1cc3e32a56eb16244f7fa770f solves the problem by adding the "Search" button to the dropdown menu if the screen is too small.

I've also done a complete rewriting of the JS code to make it more clear.

I'll release a new version of the module as soon as Humhub 1.15.0-beta.2 is released because it contains changes in the CSS for the users online indication: https://github.com/humhub/humhub/blob/develop/CHANGELOG-DEV.md

**Comment by felixhahnweilheim** [comment]
Ok, sounds great.
